### PR TITLE
[W-10592639] first release

### PR DESCRIPTION
**Pull request by cheungaryk**
ref: W-10592639

- add Github action workflow that create automatic releases:
  - when a non-master branch is pushed, create a prerelease
  - when the master branch is pushed (aka PR is merged), create a release
- remove most rules (because we want to start slow)
- update readme

The releases will be used by the onboarding script to download the latest rulesets.

https://www.loom.com/share/9e5cd38f7a9343078a4a892b68550709

### CODE REVIEW

**Comment by sanderson-sfdc** [comment]
@cheungaryk - is there a way I can test this?

**Comment by cheungaryk** [comment]
> @cheungaryk - is there a way I can test this?

what do you mean by "this"?

If you mean the github action, change the condition of **.github/workflows/release.yml** to `on: [push]` to trigger the workflow at every push. Do a push, and the workflow [ran successfully](https://github.com/mulesoft/dev-docs-writing-style/runs/7419840810?check_suite_focus=true) which [tagged and created releases](https://github.com/mulesoft/dev-docs-writing-style/releases).

If you mean to test the writing style, open a docs repo like docs-general and create a test branch. Follow [the readme](https://github.com/mulesoft/dev-docs-writing-style/blob/master/README.adoc) to set up your branch, push, and you should get an email telling you what Vale has failed. You can see the Github action running with the result similar to [this job](https://github.com/mulesoft/docs-general/runs/7419270662?check_suite_focus=true). (Alternatively, clone https://github.com/mulesoft/docs-general/tree/w-10592639-vale, make some changes, and push.) As you can see, there are a lot of errors, so one of the purposes of this PR is to start slow and remove most of the rules, and we will maybe add 1 rule each week.

**Comment by sanderson-sfdc** [comment]
Great, thanks.  It looks so great, @cheungaryk, I really appreciate all the work on this.

**Comment by cheungaryk** [comment]
please watch https://www.loom.com/share/034d8ce806994a46b768f3843ec59369 on how this auto-linter will be used.

**Comment by cheungaryk** [comment]
ready to be reviewed again. Please refer to the video in the main PR description for the latest (instead of the comments)

**Review by sanderson-sfdc — APPROVED** [review]
Nice job; I'm looking forward to seeing you roll this out to writers.

**Pull request merged**
